### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by AnotherWayIn** [jonasehrlich/ek-scraper#7]
i always get 0 results. does it still work?

**Comment by jonasehrlich** [comment]
Haven't tried it in quite some time, especially not after the rebranding from Ebay Kleinanzeigen to [kleinanzeigen.de](kleinanzeigen.de). So it probably does not work anymore I'll have a look at it tonight and see what changes are needed.

**Comment by jonasehrlich** [comment]
I had a look at the project and there was indeed a small change in the website structure. That should be addressed in #9. One reason to return 0 results could be that you did not use the correct kleinanzeigen.de URL, because the examples still refer to ebay-kleinanzeigen.de. 

I published [v0.1.0](https://github.com/jonasehrlich/ek-scraper/releases/tag/v0.1.0) to PyPI. This replaces all references to Ebay Kleinanzeigen with  kleinanzeigen.de and fixes the error when parsing the ad items.
